//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNou
{
    using System;
    using System.Collections.Generic;
    
    public partial class Angajati
    {
        public int id_angajat { get; set; }
        public string nume_angajat { get; set; }
        public Nullable<long> CNP { get; set; }
        public Nullable<int> nr_telefon { get; set; }
        public string adresa_email { get; set; }
        public Nullable<System.DateTime> data_angajarii { get; set; }
        public string username { get; set; }
        public string parola { get; set; }
        public Nullable<bool> rol { get; set; }
    }
}
