//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNou
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dotari_Camera
    {
        public int id_dot_cam { get; set; }
        public Nullable<int> id_camera { get; set; }
        public Nullable<int> id_dotare { get; set; }
    
        public virtual Dotari Dotari { get; set; }
        public virtual Tip_Camera Tip_Camera { get; set; }
    }
}
