//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNou
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oferte
    {
        public int id_oferta { get; set; }
        public Nullable<System.DateTime> data_inceput { get; set; }
        public Nullable<System.DateTime> data_incheiere { get; set; }
        public Nullable<double> pret { get; set; }
        public Nullable<int> id_camera { get; set; }
    
        public virtual Tip_Camera Tip_Camera { get; set; }
    }
}
