//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNou
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervare()
        {
            this.Serviciu_Rezervare = new HashSet<Serviciu_Rezervare>();
            this.Rezervare_Camera = new HashSet<Rezervare_Camera>();
        }
    
        public int id_rezervare { get; set; }
        public Nullable<System.DateTime> data_inceput { get; set; }
        public Nullable<System.DateTime> data_incheiere { get; set; }
        public string status_rezervare { get; set; }
        public Nullable<int> id_client { get; set; }
    
        public virtual Clienti Clienti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serviciu_Rezervare> Serviciu_Rezervare { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervare_Camera> Rezervare_Camera { get; set; }
    }
}
