//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelNou
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicii_Suplimentare
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Servicii_Suplimentare()
        {
            this.Serviciu_Rezervare = new HashSet<Serviciu_Rezervare>();
        }
    
        public int id_serviciu { get; set; }
        public string denumire_serviciu { get; set; }
        public Nullable<double> pret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Serviciu_Rezervare> Serviciu_Rezervare { get; set; }
    }
}
